# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This GitHub action will deploy the Data Beans demo to a Google Cloud Project.
# For more information, see: https://cloud.google.com/iam/docs/workload-identity-federation
#
# To use this action, you need to create the following secrets in your GitHub repository:
#
# - GCP_PROJECT_ID: The ID of your Google Cloud project.
# - GCP_PROJECT_NUMBER: The number of your Google Cloud project.
# - GCP_WORKLOAD_IDENTITY_PROVIDER: The full name of the Workload Identity Pool Provider.
# - GCP_SERVICE_ACCOUNT: The email address of the service account to impersonate.

name: Deploy to Google Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform -chdir=terraform init

      - name: Terraform Validate
        run: terraform -chdir=terraform validate

      - name: Terraform Apply
        run: |
          terraform -chdir=terraform apply -auto-approve \
            -var="gcp_account_name=${{ secrets.GCP_SERVICE_ACCOUNT }}" \
            -var="project_id=${{ secrets.GCP_PROJECT_ID }}" \
            -var="project_number=${{ secrets.GCP_PROJECT_NUMBER }}" \
            -var="org_id=0"
